services:
  db:
    image: postgres:14
    container_name: prediction_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: prediction_market
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: prediction_backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:mypassword@db:5432/prediction_market
      NODE_ENV: development
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: prediction_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:5000"

volumes:
  pg_data:
